inherit_from: .rubocop-bundler.yml

AllCops:
  Exclude:
    - !ruby/regexp /(vendor|bundle|bin|db|tmp)\/.*/

Metrics/BlockLength:
  Exclude:
    - "db/migrations/*.rb"
    - "spec/**/*.rb"

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

# TODO
# Performance/UnfreezeString:
#   Enabled: false
